"use client";

import { Archive, ArrowLeft, CalendarDays, Pencil } from "lucide-react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ProjectFormDialog } from "@/components/admin/ProjectFormDialog";
import { ProjectTeamSection } from "@/components/admin/ProjectTeamSection";
import { formatRequestDateTime } from "@/lib/request-display";
import { projectApi, ProjectApiError, type EmployeeOption, type Project, type ProjectInput, type ProjectMember } from "@/lib/project-api";

export default function ProjectDetailsPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [project, setProject] = useState<Project | null>(null); const [members, setMembers] = useState<ProjectMember[]>([]); const [employees, setEmployees] = useState<EmployeeOption[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [teamError, setTeamError] = useState(""); const [reload, setReload] = useState(0); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [formError, setFormError] = useState("");
  useEffect(() => { let active = true; async function load() { setLoading(true); setError(""); try { const [projectData, memberData, employeeData] = await Promise.all([projectApi.details(id), projectApi.members(id), projectApi.employees()]); if (active) { setProject(projectData); setMembers(memberData); setEmployees(employeeData); } } catch (cause) { if (!active) return; if (cause instanceof ProjectApiError && cause.status === 401) router.replace("/login"); else if (cause instanceof ProjectApiError && cause.status === 404) setError("Project not found."); else setError(cause instanceof Error ? cause.message : "Unable to load project."); } finally { if (active) setLoading(false); } } load(); return () => { active = false; }; }, [id, reload, router]);
  function sessionExpired(cause: unknown) { if (cause instanceof ProjectApiError && cause.status === 401) { router.replace("/login"); return true; } return false; }
  async function update(input: ProjectInput) { if (!project) return; setBusy(true); setFormError(""); try { setProject(await projectApi.update(project.id, input)); setEditing(false); } catch (cause) { if (!sessionExpired(cause)) setFormError(cause instanceof Error ? cause.message : "Unable to update project."); } finally { setBusy(false); } }
  async function archive() { if (!project || !window.confirm(`Archive ${project.name}? Its project information and team will become read-only.`)) return; setBusy(true); setError(""); try { setProject(await projectApi.archive(project.id)); } catch (cause) { if (!sessionExpired(cause)) setError(cause instanceof Error ? cause.message : "Unable to archive project."); } finally { setBusy(false); } }
  async function addMember(employeeId: number) { if (!project) return; setBusy(true); setTeamError(""); try { const member = await projectApi.addMember(project.id, employeeId); setMembers((current) => [...current, member].sort((a, b) => a.fullName.localeCompare(b.fullName) || a.employeeId - b.employeeId)); } catch (cause) { if (!sessionExpired(cause)) setTeamError(cause instanceof Error ? cause.message : "Unable to add team member."); } finally { setBusy(false); } }
  async function removeMember(member: ProjectMember) { if (!project || !window.confirm(`Remove ${member.fullName} from this project? The Employee account will not be deleted.`)) return; setBusy(true); setTeamError(""); try { await projectApi.removeMember(project.id, member.employeeId); setMembers((current) => current.filter((item) => item.employeeId !== member.employeeId)); } catch (cause) { if (!sessionExpired(cause)) setTeamError(cause instanceof Error ? cause.message : "Unable to remove team member."); } finally { setBusy(false); } }
  if (loading) return <section className="rounded-xl border border-divider bg-surface px-6 py-10 text-sm text-secondary" role="status">Loading project...</section>;
  if (error || !project) return <section className="rounded-xl border border-divider bg-surface px-6 py-10" role="alert"><p className="text-sm text-[#B42318]">{error || "Unable to load project."}</p><button type="button" onClick={() => setReload((value) => value + 1)} className="mt-3 text-sm font-medium text-accent underline">Retry</button></section>;
  const archived = project.status === "ARCHIVED";
  return <div className="space-y-5"><Link href="/projects" className="inline-flex items-center gap-2 text-sm font-medium text-accent hover:underline"><ArrowLeft size={17} />Back to Projects</Link><section className="rounded-xl border border-divider bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-semibold">{project.name}</h2><span className={`rounded-full px-3 py-1 text-xs font-semibold ${archived ? "bg-background text-secondary" : "bg-[#E9F8F0] text-[#227A4B]"}`}>{archived ? "Archived" : "Active"}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-secondary">{project.description ?? "No description provided."}</p></div>{!archived && <div className="flex gap-2"><button type="button" onClick={() => { setFormError(""); setEditing(true); }} className="inline-flex h-10 items-center gap-2 rounded-[9px] bg-nav-active px-4 text-sm font-medium text-accent"><Pencil size={16} />Edit</button><button type="button" disabled={busy} onClick={archive} className="inline-flex h-10 items-center gap-2 rounded-[9px] border border-divider px-4 text-sm font-medium text-secondary hover:bg-nav-hover"><Archive size={16} />Archive</button></div>}</div><dl className="mt-6 grid gap-4 border-t border-divider pt-5 sm:grid-cols-2"><div><dt className="flex items-center gap-2 text-xs text-secondary"><CalendarDays size={15} />Created</dt><dd className="mt-1 text-sm font-medium">{formatRequestDateTime(project.createdAt)}</dd></div><div><dt className="flex items-center gap-2 text-xs text-secondary"><CalendarDays size={15} />Last Updated</dt><dd className="mt-1 text-sm font-medium">{formatRequestDateTime(project.updatedAt)}</dd></div></dl>{archived && <p className="mt-5 rounded-[9px] bg-background px-4 py-3 text-sm text-secondary">This project is archived. Project information and team membership are read-only.</p>}</section><ProjectTeamSection members={members} employees={employees} readOnly={archived} busy={busy} error={teamError} onAdd={addMember} onRemove={removeMember} />{editing && <ProjectFormDialog project={project} busy={busy} error={formError} onClose={() => setEditing(false)} onSave={update} />}</div>;
}
