spring.application.name=backend

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:request_management}
spring.datasource.username=${POSTGRES_USER:request_user}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
