"use client";

import { Activity, CalendarDays, CheckSquare2, ChevronDown, Send, UserRound } from "lucide-react";
import { FormEvent, ReactNode, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { apiFetch, getApiErrorMessage } from "@/lib/api-client";
import { projectApi, type ProjectTaskMember, type ProjectWorkType } from "@/lib/project-api";
import { formatRequestDateTime, REQUEST_PRIORITY_LABELS, REQUEST_STATUSES, REQUEST_STATUS_LABELS, UNASSIGNED_LABEL, type RequestPriority, type RequestStatus } from "@/lib/request-display";

type TimelineEntry = { oldStatus: RequestStatus | null; newStatus: RequestStatus; changedByName: string; changeNote: string | null; changedAt: string };
type Comment = { id: number; text: string; authorName: string; authorRole: "ADMIN" | "EMPLOYEE"; createdAt: string };
type TaskDetails = { id: number; title: string; description: string; workType: ProjectWorkType; priority: RequestPriority; status: RequestStatus; assignedToId: number | null; assignedToName: string | null; createdById: number; createdByName: string; projectId: number; projectName: string; projectStatus: "ACTIVE" | "ARCHIVED"; createdAt: string; updatedAt: string; timeline: TimelineEntry[]; comments: Comment[]; internalNotes?: Comment[] };
const card = "rounded-xl border border-divider bg-surface p-6";
const control = "h-11 w-full rounded-[9px] border border-divider bg-surface px-3.5 text-sm outline-none focus:border-accent";
const workTypeLabels: Record<ProjectWorkType, string> = { TASK: "Task", BUG: "Bug", IMPROVEMENT: "Improvement" };

export function ProjectTaskDetails({ projectId, taskId, access = "employee", onUpdated }: { projectId: number; taskId: string; access?: "employee" | "admin"; onUpdated?: () => void; onClose?: () => void }) {
  const router = useRouter();
  const [task, setTask] = useState<TaskDetails | null>(null); const [members, setMembers] = useState<Pick<ProjectTaskMember, "employeeId" | "fullName" | "active">[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notFound, setNotFound] = useState(false); const [reload, setReload] = useState(0);
  const [status, setStatus] = useState<RequestStatus>("NEW"); const [changeNote, setChangeNote] = useState(""); const [showNote, setShowNote] = useState(false); const [statusBusy, setStatusBusy] = useState(false); const [statusError, setStatusError] = useState("");
  const [assigneeBusy, setAssigneeBusy] = useState(false); const [assigneeError, setAssigneeError] = useState("");
  const [comment, setComment] = useState(""); const [commentBusy, setCommentBusy] = useState(false); const [commentError, setCommentError] = useState("");
  const [internalNote, setInternalNote] = useState(""); const [internalBusy, setInternalBusy] = useState(false); const [internalError, setInternalError] = useState("");
  const base = access === "admin" ? `/api/projects/${projectId}/tasks/${encodeURIComponent(taskId)}` : `/api/projects/mine/${projectId}/tasks/${encodeURIComponent(taskId)}`;

  useEffect(() => { let active = true; async function load() { setLoading(true); setError(""); setNotFound(false); try { const response = await apiFetch(base, { cache: "no-store" }); if (response.status === 401) { router.replace("/login"); return; } if (response.status === 404) { setNotFound(true); return; } if (!response.ok) throw new Error("Unable to load task details."); const loaded: TaskDetails = await response.json(); const memberData = access === "admin" ? await projectApi.members(projectId) : await projectApi.taskMembers(projectId); if (active) { setTask(loaded); setStatus(loaded.status); setMembers(memberData.map((member) => ({ employeeId: member.employeeId, fullName: member.fullName, active: member.active }))); } } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : "Unable to load task details."); } finally { if (active) setLoading(false); } } load(); return () => { active = false; }; }, [access, base, projectId, reload, router]);

  async function changeStatus(event: FormEvent) { event.preventDefault(); if (!task || statusBusy) return; setStatusBusy(true); setStatusError(""); try { const response = await apiFetch(`${base}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, changeNote: changeNote.trim() || null }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, "Unable to change status.")); const updated: TaskDetails = await response.json(); setTask(updated); setStatus(updated.status); setChangeNote(""); setShowNote(false); onUpdated?.(); } catch (cause) { setStatusError(cause instanceof Error ? cause.message : "Unable to change status."); } finally { setStatusBusy(false); } }
  async function reassign(assignedToId: number) { if (!task || assigneeBusy) return; setAssigneeBusy(true); setAssigneeError(""); try { const response = await apiFetch(`${base}/assignee`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assignedToId }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, "Unable to reassign task.")); setTask(await response.json()); onUpdated?.(); } catch (cause) { setAssigneeError(cause instanceof Error ? cause.message : "Unable to reassign task."); } finally { setAssigneeBusy(false); } }
  async function addEntry(event: FormEvent, internal: boolean) { event.preventDefault(); if (!task || (internal ? internalBusy : commentBusy)) return; const text = (internal ? internalNote : comment).trim(); const setEntryError = internal ? setInternalError : setCommentError; if (!text) { setEntryError(internal ? "Internal note is required." : "Comment is required."); return; } (internal ? setInternalBusy : setCommentBusy)(true); setEntryError(""); try { const response = await apiFetch(`${base}/${internal ? "internal-notes" : "comments"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text }) }); if (!response.ok) throw new Error(await getApiErrorMessage(response, "Unable to save entry.")); const added: Comment = await response.json(); setTask({ ...task, ...(internal ? { internalNotes: [...(task.internalNotes ?? []), added] } : { comments: [...task.comments, added] }) }); (internal ? setInternalNote : setComment)(""); } catch (cause) { setEntryError(cause instanceof Error ? cause.message : "Unable to save entry."); } finally { (internal ? setInternalBusy : setCommentBusy)(false); } }

  if (loading) return <section className={card} role="status">Loading task details...</section>;
  if (notFound) return <section className={card}><h2 className="text-lg font-semibold">Task not found</h2><p className="mt-2 text-sm text-secondary">This task is unavailable or you no longer have Project access.</p></section>;
  if (error || !task) return <section className={card} role="alert"><p className="text-sm text-[#B42318]">{error || "Unable to load task."}</p><button type="button" onClick={() => setReload((value) => value + 1)} className="mt-3 text-sm font-medium text-accent underline">Retry</button></section>;
  const readOnly = task.projectStatus === "ARCHIVED"; const activeMembers = members.filter((member) => member.active);
  return <div className="space-y-5">
    <header className={card}><p className="text-sm font-medium text-accent">{task.projectName}</p><div className="mt-2 flex flex-wrap items-start justify-between gap-5"><div><h1 className="text-2xl font-semibold">{task.title}</h1><p className="mt-1 text-xs font-semibold uppercase tracking-wide text-secondary">{workTypeLabels[task.workType]} · Task #{task.id}</p></div>{readOnly ? <span className="rounded-full bg-nav-active px-3 py-1.5 text-sm font-semibold text-accent">{REQUEST_STATUS_LABELS[task.status]}</span> : <form onSubmit={changeStatus} className="w-full max-w-xs space-y-2"><div className="flex gap-2"><select aria-label="Task status" value={status} onChange={(event) => setStatus(event.target.value as RequestStatus)} className={control}>{REQUEST_STATUSES.map((value) => <option key={value} value={value}>{REQUEST_STATUS_LABELS[value]}</option>)}</select><button type="submit" disabled={statusBusy || status === task.status} className="h-11 shrink-0 rounded-[9px] bg-accent px-4 text-sm font-medium text-white disabled:opacity-50">{statusBusy ? "Updating..." : "Update Status"}</button></div><button type="button" onClick={() => setShowNote((value) => !value)} className="inline-flex items-center gap-1 text-xs font-medium text-accent"><ChevronDown size={14} className={showNote ? "rotate-180" : ""} />Add Note</button>{showNote && <textarea rows={2} value={changeNote} maxLength={10000} onChange={(event) => setChangeNote(event.target.value)} placeholder="Optional status change note" className={`${control} min-h-16 py-2`} />}{statusError && <p role="alert" className="text-xs text-[#B42318]">{statusError}</p>}</form>}</div>{readOnly && <p className="mt-5 rounded-[9px] bg-background px-4 py-3 text-sm text-secondary">This Project is archived. Task activity is read-only.</p>}</header>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(300px,.7fr)]"><main className="space-y-6">
      <section className={card}><h2 className="flex items-center gap-2 text-lg font-semibold"><CheckSquare2 size={19} className="text-accent" />Description</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-secondary">{task.description}</p></section>
      <section className={card}><h2 className="flex items-center gap-2 text-lg font-semibold"><Activity size={19} className="text-accent" />Activity</h2><ol className="mt-5"><li className="grid grid-cols-[14px_1fr] gap-3"><TimelineNode connected={task.timeline.length > 0} /><div className="pb-5"><p className="text-sm font-semibold">Task created</p><time className="text-xs text-secondary">{formatRequestDateTime(task.createdAt)}</time><p className="mt-1 text-xs text-secondary">Created by {task.createdByName}</p></div></li>{task.timeline.map((entry, index) => <li key={`${entry.changedAt}-${index}`} className="grid grid-cols-[14px_1fr] gap-3"><TimelineNode connected={index < task.timeline.length - 1} /><div className="pb-5"><p className="text-sm font-semibold">{entry.oldStatus ? REQUEST_STATUS_LABELS[entry.oldStatus] : "New"} → {REQUEST_STATUS_LABELS[entry.newStatus]}</p><time className="text-xs text-secondary">{formatRequestDateTime(entry.changedAt)}</time>{entry.changeNote && <p className="mt-1 text-xs text-secondary">{entry.changeNote}</p>}<p className="mt-1 text-xs text-secondary">Changed by {entry.changedByName}</p></div></li>)}</ol></section>
      <Conversation title="Comments" items={task.comments} empty="No comments yet." composer={!readOnly ? <Composer value={comment} onChange={setComment} busy={commentBusy} error={commentError} placeholder="Add a comment..." onSubmit={(event) => addEntry(event, false)} /> : null} />
      {access === "admin" && <Conversation title="Internal Notes (Admin Only)" items={task.internalNotes ?? []} empty="No internal notes yet." composer={!readOnly ? <Composer value={internalNote} onChange={setInternalNote} busy={internalBusy} error={internalError} placeholder="Add an internal note..." onSubmit={(event) => addEntry(event, true)} /> : null} />}
    </main><aside><section className={card}><h2 className="text-lg font-semibold">Task Details</h2><dl className="mt-5 space-y-5"><div><dt className="text-xs text-secondary">Assignee</dt>{readOnly ? <dd className="mt-1 text-sm font-semibold">{task.assignedToName ?? UNASSIGNED_LABEL}</dd> : <dd className="mt-2"><select value={task.assignedToId ?? ""} disabled={assigneeBusy} onChange={(event) => reassign(Number(event.target.value))} className={control}><option value="" disabled>Unassigned</option>{activeMembers.map((member) => <option key={member.employeeId} value={member.employeeId}>{member.fullName}</option>)}</select>{assigneeError && <p role="alert" className="mt-2 text-xs text-[#B42318]">{assigneeError}</p>}</dd>}</div><Detail label="Priority" value={REQUEST_PRIORITY_LABELS[task.priority]} /><Detail label="Work Type" value={workTypeLabels[task.workType]} /><div><dt className="text-xs text-secondary">Created by</dt><dd className="mt-1 flex items-center gap-2 text-sm font-semibold"><UserRound size={16} className="text-accent" />{task.createdByName}</dd></div><div><dt className="text-xs text-secondary">Created at</dt><dd className="mt-1 flex items-center gap-2 text-sm font-semibold"><CalendarDays size={16} className="text-accent" />{formatRequestDateTime(task.createdAt)}</dd></div><Detail label="Project" value={task.projectName} /></dl></section></aside></div>
  </div>;
}

function Conversation({ title, items, empty, composer }: { title: string; items: Comment[]; empty: string; composer: ReactNode }) { return <section className={card}><h2 className="text-lg font-semibold">{title}</h2><div className="mt-4 divide-y divide-divider">{items.length === 0 && <p className="py-4 text-sm text-secondary">{empty}</p>}{items.map((item) => <article key={item.id} className="flex gap-3 py-4"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-avatar text-xs font-semibold text-secondary">{item.authorName.trim().charAt(0) || "?"}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold">{item.authorName}</p><time className="text-xs text-secondary">{formatRequestDateTime(item.createdAt)}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{item.text}</p></div></article>)}</div>{composer}</section>; }
function Composer({ value, onChange, busy, error, placeholder, onSubmit }: { value: string; onChange: (value: string) => void; busy: boolean; error: string; placeholder: string; onSubmit: (event: FormEvent) => void }) { return <form onSubmit={onSubmit} className="mt-4"><div className="flex gap-3"><textarea rows={2} maxLength={10000} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className={`${control} min-h-11 flex-1 resize-y py-3`} /><button type="submit" disabled={busy} aria-label="Send" className="flex h-11 w-11 items-center justify-center rounded-[9px] bg-accent text-white disabled:opacity-60"><Send size={18} /></button></div>{error && <p role="alert" className="mt-2 text-sm text-[#B42318]">{error}</p>}</form>; }
function TimelineNode({ connected }: { connected: boolean }) { return <div className="flex flex-col items-center"><span className="h-3.5 w-3.5 rounded-full bg-accent" />{connected && <span className="min-h-10 w-0.5 flex-1 bg-[#C8D5F5]" />}</div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-secondary">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>; }
